version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy

########################### VOLUMES

########################### SERVICES
services:

# Test nordlynx
  nordlynx:
    container_name: nordlynx
    image: nordlynx
    restart: unless-stopped
    networks:
      - t2_proxy
#    security_opt:
#      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    environment:
     - TZ=$TZ
     - NL_USERNAME=$NL_USERNAME
     - NL_PASSWORD=$NL_PASSWORD
     - NL_COUNTRY=$NL_COUNTRY
     - NL_GROUP=$NL_GROUP
